### ISSUE TITLE
Improve Results

### ISSUE THREAD

**Issue by joclement** [joclement/master_thesis#109]
- [ ] Run Tsfresh model with FDR level `0.05` and `n_significant=5`, #115 
- [x] #104, especially using the Sakoe-Chiba Band for Raw-kNN-DTW
- [ ] Drop a few low impact features from RelFip und retune it, #108 
- [ ] Tune RelFip for Noise Data Classification, #113
